export const BIBLE_BOOKS = [
  { name: "Génesis", abbr: "Gn", ch: 50, cat: 'ley' }, 
  { name: "Éxodo", abbr: "Ex", ch: 40, cat: 'ley' }, 
  { name: "Levítico", abbr: "Lv", ch: 27, cat: 'ley' }, 
  { name: "Números", abbr: "Nm", ch: 36, cat: 'ley' }, 
  { name: "Deuteronomio", abbr: "Dt", ch: 34, cat: 'ley' }, 
  { name: "Josué", abbr: "Jos", ch: 24, cat: 'hist' }, 
  { name: "Jueces", abbr: "Jue", ch: 21, cat: 'hist' }, 
  { name: "Rut", abbr: "Rt", ch: 4, cat: 'hist' }, 
  { name: "1 Samuel", abbr: "1Sm", ch: 31, cat: 'hist' }, 
  { name: "2 Samuel", abbr: "2Sm", ch: 24, cat: 'hist' }, 
  { name: "1 Reyes", abbr: "1Re", ch: 22, cat: 'hist' }, 
  { name: "2 Reyes", abbr: "2Re", ch: 25, cat: 'hist' }, 
  { name: "1 Crónicas", abbr: "1Cr", ch: 29, cat: 'hist' }, 
  { name: "2 Crónicas", abbr: "2Cr", ch: 36, cat: 'hist' }, 
  { name: "Esdras", abbr: "Esd", ch: 10, cat: 'hist' }, 
  { name: "Nehemías", abbr: "Neh", ch: 13, cat: 'hist' }, 
  { name: "Ester", abbr: "Est", ch: 10, cat: 'hist' }, 
  { name: "Job", abbr: "Job", ch: 42, cat: 'poe' }, 
  { name: "Salmos", abbr: "Sal", ch: 150, cat: 'poe' }, 
  { name: "Proverbios", abbr: "Pr", ch: 31, cat: 'poe' }, 
  { name: "Eclesiastés", abbr: "Ec", ch: 12, cat: 'poe' }, 
  { name: "Cantares", abbr: "Cnt", ch: 8, cat: 'poe' }, 
  { name: "Isaías", abbr: "Is", ch: 66, cat: 'prof' }, 
  { name: "Jeremías", abbr: "Jer", ch: 52, cat: 'prof' }, 
  { name: "Lamentaciones", abbr: "Lam", ch: 5, cat: 'prof' }, 
  { name: "Ezequiel", abbr: "Ez", ch: 48, cat: 'prof' }, 
  { name: "Daniel", abbr: "Dn", ch: 12, cat: 'prof' }, 
  { name: "Oseas", abbr: "Os", ch: 14, cat: 'prof' }, 
  { name: "Joel", abbr: "Jl", ch: 3, cat: 'prof' }, 
  { name: "Amós", abbr: "Am", ch: 9, cat: 'prof' }, 
  { name: "Abdías", abbr: "Abd", ch: 1, cat: 'prof' }, 
  { name: "Jonás", abbr: "Jon", ch: 4, cat: 'prof' }, 
  { name: "Miqueas", abbr: "Miq", ch: 7, cat: 'prof' }, 
  { name: "Nahúm", abbr: "Nah", ch: 3, cat: 'prof' }, 
  { name: "Habacuc", abbr: "Hab", ch: 3, cat: 'prof' }, 
  { name: "Sofonías", abbr: "Sof", ch: 3, cat: 'prof' }, 
  { name: "Hageo", abbr: "Hag", ch: 2, cat: 'prof' }, 
  { name: "Zacarías", abbr: "Zac", ch: 14, cat: 'prof' }, 
  { name: "Malaquías", abbr: "Mal", ch: 4, cat: 'prof' }, 
  { name: "Mateo", abbr: "Mt", ch: 28, cat: 'evang' }, 
  { name: "Marcos", abbr: "Mk", ch: 16, cat: 'evang' }, 
  { name: "Lucas", abbr: "Lk", ch: 24, cat: 'evang' }, 
  { name: "Juan", abbr: "Jn", ch: 21, cat: 'evang' }, 
  { name: "Hechos", abbr: "Hch", ch: 28, cat: 'h_nt' }, 
  { name: "Romanos", abbr: "Rom", ch: 16, cat: 'epist' }, 
  { name: "1 Corintios", abbr: "1Co", ch: 16, cat: 'epist' }, 
  { name: "2 Corintios", abbr: "2Co", ch: 13, cat: 'epist' }, 
  { name: "Gálatas", abbr: "Gal", ch: 6, cat: 'epist' }, 
  { name: "Efesios", abbr: "Eph", ch: 6, cat: 'epist' }, 
  { name: "Filipenses", abbr: "Php", ch: 4, cat: 'epist' }, 
  { name: "Colosenses", abbr: "Col", ch: 4, cat: 'epist' }, 
  { name: "1 Tesalonicenses", abbr: "1Th", ch: 5, cat: 'epist' }, 
  { name: "2 Tesalonicenses", abbr: "2Th", ch: 3, cat: 'epist' }, 
  { name: "1 Timoteo", abbr: "1Ti", ch: 6, cat: 'epist' }, 
  { name: "2 Timoteo", abbr: "2Ti", ch: 4, cat: 'epist' }, 
  { name: "Tito", abbr: "Tit", ch: 3, cat: 'epist' }, 
  { name: "Filemón", abbr: "Phm", ch: 1, cat: 'epist' }, 
  { name: "Hebreos", abbr: "Heb", ch: 13, cat: 'epist' }, 
  { name: "Santiago", abbr: "Jam", ch: 5, cat: 'epist' }, 
  { name: "1 Pedro", abbr: "1Pe", ch: 5, cat: 'epist' }, 
  { name: "2 Pedro", abbr: "2Pe", ch: 3, cat: 'epist' }, 
  { name: "1 Juan", abbr: "1Jo", ch: 5, cat: 'epist' }, 
  { name: "2 Juan", abbr: "2Jo", ch: 1, cat: 'epist' }, 
  { name: "3 Juan", abbr: "3Jo", ch: 1, cat: 'epist' }, 
  { name: "Judas", abbr: "Jud", ch: 1, cat: 'epist' }, 
  { name: "Apocalipsis", abbr: "Rev", ch: 22, cat: 'prof_nt' }
];

export const BIBLE_CAT_COLORS = { 
  ley:'#d68910', hist:'#c0392b', poe:'#8e44ad', prof:'#92144d', 
  evang:'#2980b9', h_nt: '#3498db', epist:'#27ae60', prof_nt:'#16a085', 
  default: '#7f8c8d' 
};